export { default as HeroBg } from "./HeroBg.png";
export { default as Bbc } from "./Bbc.png";
export { default as Rakuten } from "./Rakuten.png";
export { default as Spotify } from "./Spotify.png";
export { default as Tiktok } from "./Tiktok.png";
export { default as Trivago } from "./Trivago.png";
export { default as OfferImageOne } from "./OfferImageOne.png";
export { default as OfferImageTwo } from "./OfferImageTwo.png";
export { default as OfferImageThree } from "./OfferImageThree.png";
export { default as OfferBg } from "./OfferBg.png";
export { default as BannerImage } from "./BannerImage.png";
export { default as FooterIBg } from "./FooterIBg.png";
export { default as LinkedinIcon } from "./Link → linkedin.svg.png";
export { default as TwitterIcon } from "./Link → twitter.svg.png";
export { default as FacebookIcon } from "./Link → facebook.svg.png";
export { default as InstagramIcon } from "./Link → instagram.svg.png";
export { default as GooglePlayStore } from "./Link.png";
export { default as AppStore } from "./Link (1).png";
