export { default as Hero } from "./Hero";
export { default as Sidebar } from "./Sidebar";
export { default as Portfolio } from "./Portfolio";
export { default as TicketInfo } from "./TicketInfo";
export { default as WhatMore } from "./WhatMore";
export { default as Contact } from "./Contact";
export { default as Footer } from "./Footer";
export { default as GetStarted } from "./GetStarted";
export { default as Faq } from "./Faq";
